// electron 进程内常量统一对外桶出口
export { API_BASE_URL, REQUEST_TIMEOUT_MS } from './api';
export {
  ACCEPTED_IMAGE_EXTENSIONS,
  MAX_REFERENCE_IMAGE_SIZE,
  MAX_RESULT_IMAGE_SIZE,
  MIME_EXTENSIONS,
} from './media';
export {
  ID_PATTERN,
  MAX_CHARACTER_ACTION_LENGTH,
  MAX_NAME_LENGTH,
  MAX_PROMPT_LENGTH,
  MAX_STORED_PROMPT_LENGTH,
  MAX_TEXT_LENGTH,
  MAX_TITLE_LENGTH,
} from './text';
export { WORKSPACE_ASSETS_SUBDIRECTORY } from './paths';
