export type {
  CredentialService,
  CredentialStatus,
  DesktopApi,
  DesktopSettings,
  SavedFileResult,
  SaveFileRequest,
  SetCredentialRequest,
} from '../../shared/desktop';
export type {
  CharacterAgentMessage,
  CharacterDraft,
  CharacterDraftField,
  CharacterDraftPatch,
  CharacterDraftUpdateResult,
  CharacterProfileProposalResult,
  CharacterWorkspaceState,
  SaveCharacterProfileRequest,
} from '../../shared/character';
export type {
  CharacterLibraryCharacter,
  CharacterLibraryVisualAsset,
  CharacterLibraryState,
  CharacterSummary,
  CreateCharacterRequest,
  DeleteCharacterRequest,
  SelectCharacterRequest,
  UpdateCharacterRequest,
} from '../../shared/character-library';
export type {
  CharacterExpressionRecord,
  CharacterExpressionSize,
  CharacterExpressionWorkspaceState,
  DeleteCharacterExpressionRequest,
  GenerateCharacterExpressionRequest,
  RenameCharacterExpressionRequest,
  UploadCharacterExpressionRequest,
} from '../../shared/character-expression';
export { CHARACTER_EXPRESSION_SIZES } from '../../shared/character-expression';
export type {
  CharacterImageRecord,
  CharacterImageSize,
  CharacterImageSource,
  CharacterPortraitImage,
  CharacterPortraitRecord,
  CharacterPortraitResolution,
  CharacterPortraitSelection,
  CharacterPortraitSize,
  CharacterPortraitTaskStatus,
  CharacterPortraitWorkspaceState,
  CharacterSheetRecord,
  CharacterVisualAssetKind,
  CharacterVisualAssetSelection,
  DeleteCharacterPortraitRequest,
  DeleteCharacterSheetRequest,
  GenerateCharacterPortraitRequest,
  GenerateCharacterSheetRequest,
  RenameCharacterVisualAssetRequest,
  SelectCharacterPortraitRequest,
  SelectCharacterSheetRequest,
  SetCharacterVisualAssetOfficialRequest,
  UploadCharacterVisualAssetRequest,
} from '../../shared/character-portrait';
export {
  CHARACTER_AGENT_ENDPOINT,
  CHARACTER_DRAFT_FIELDS,
  DEFAULT_DEEPSEEK_MODEL,
  createEmptyCharacterDraft,
  getCharacterDraftProgress,
} from '../../shared/character';
export {
  CHARACTER_PORTRAIT_RESOLUTIONS,
  CHARACTER_PORTRAIT_SIZES,
  CHARACTER_SHEET_SIZE,
} from '../../shared/character-portrait';
export type {
  CreateIllustrationTopicRequest,
  DeleteIllustrationUploadRequest,
  DeleteIllustrationTopicRequest,
  DeleteIllustrationVersionRequest,
  GenerateIllustrationRequest,
  IllustrationAgentMessage,
  IllustrationBrief,
  IllustrationBriefUpdateResult,
  IllustrationSize,
  IllustrationStyleReference,
  IllustrationTopic,
  IllustrationVersion,
  IllustrationVersionReference,
  IllustrationWorkspaceState,
  SaveIllustrationConversationRequest,
  SelectIllustrationStyleReferenceRequest,
  UpdateIllustrationTopicRequest,
  UploadedIllustration,
  UploadIllustrationRequest,
} from '../../shared/illustration';
export {
  ILLUSTRATION_AGENT_ENDPOINT,
  ILLUSTRATION_SIZES,
  ILLUSTRATION_STYLE_GUIDANCE,
  createEmptyIllustrationBrief,
} from '../../shared/illustration';
export type {
  CreateStoryRequest,
  CreateStoryShotRequest,
  DeleteStoryRequest,
  DeleteStoryShotRequest,
  DeleteStoryShotVersionRequest,
  GenerateStoryShotRequest,
  MoveStoryShotRequest,
  SaveStoryConversationRequest,
  SelectStoryShotVersionRequest,
  StoryAgentMessage,
  StoryDraft,
  StoryDraftUpdateResult,
  StoryProject,
  StoryShot,
  StoryShotContent,
  StoryShotUpdateResult,
  StoryShotVersion,
  StoryVersionReference,
  StoryboardUpdateResult,
  StoryWorkspaceState,
  UpdateStoryRequest,
  UpdateStoryShotRequest,
} from '../../shared/story';
export {
  STORY_AGENT_ENDPOINT,
  STORY_SHOT_LIMITS,
  createEmptyStoryDraft,
  createEmptyStoryShotContent,
} from '../../shared/story';
export * from './setting';
