import type { Widget, Disease, DiseaseLevel } from '../types';

/**
 * 病害数据
 */
export const diseases: Disease[] = [
  { id: 'd-001', name: '裂缝', sequence: 1, widgetId: 'w-001' },
  { id: 'd-002', name: '混凝土剥落', sequence: 2, widgetId: 'w-001' },
  { id: 'd-003', name: '钢筋锈蚀', sequence: 3, widgetId: 'w-001' },
  { id: 'd-004', name: '变形', sequence: 4, widgetId: 'w-001' },
  { id: 'd-005', name: '渗水', sequence: 5, widgetId: 'w-001' },
  { id: 'd-006', name: '支座老化', sequence: 6, widgetId: 'w-001' },
];

/**
 * 病害等级数据
 */
export const diseaseLevels: Record<string, DiseaseLevel[]> = {
  'd-001': [
    { id: 'dl-001', scale: 1, diseaseId: 'd-001', quantifier: '≤0.1mm', qualitative: '轻微裂缝，不影响结构安全' },
    { id: 'dl-002', scale: 2, diseaseId: 'd-001', quantifier: '0.1-0.2mm', qualitative: '一般裂缝，需观察' },
    { id: 'dl-003', scale: 3, diseaseId: 'd-001', quantifier: '>0.2mm', qualitative: '严重裂缝，需及时处理' },
  ],
  'd-002': [
    { id: 'dl-004', scale: 1, diseaseId: 'd-002', quantifier: '面积<1%', qualitative: '局部剥落，轻微影响' },
    { id: 'dl-005', scale: 2, diseaseId: 'd-002', quantifier: '面积1-5%', qualitative: '中等剥落，需关注' },
    { id: 'dl-006', scale: 3, diseaseId: 'd-002', quantifier: '面积>5%', qualitative: '严重剥落，需及时修复' },
  ],
  'd-003': [
    { id: 'dl-007', scale: 1, diseaseId: 'd-003', quantifier: '轻微锈蚀', qualitative: '表面有锈迹，未影响截面' },
    { id: 'dl-008', scale: 2, diseaseId: 'd-003', quantifier: '中度锈蚀', qualitative: '截面损失<5%，需关注' },
    { id: 'dl-009', scale: 3, diseaseId: 'd-003', quantifier: '严重锈蚀', qualitative: '截面损失>5%，需立即处理' },
  ],
};

/**
 * 桥梁构件数据
 */
export const bridgeWidgets: Widget[] = [
  // 梁式桥（beam-bridge）
  { id: 'beam-001', name: '上部承重构件(主梁、挂梁)', sequence: 1, weight: 0.70, type: 'upper', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-002', name: '上部一般构件(湿接缝、横隔板等)', sequence: 2, weight: 0.18, type: 'upper', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-003', name: '支座', sequence: 3, weight: 0.12, type: 'upper', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'beam-bridge' },
  { id: 'beam-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'beam-bridge' },

  // 板拱桥（slab-arch-bridge）
  { id: 'slabArch-001', name: '主拱圈', sequence: 1, weight: 0.70, type: 'upper', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-002', name: '拱上结构', sequence: 2, weight: 0.20, type: 'upper', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-003', name: '桥面板', sequence: 3, weight: 0.10, type: 'upper', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },
  { id: 'slabArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'slab-arch-bridge' },

  // 肋拱桥（ribbed-arch-bridge）
  { id: 'ribbedArch-001', name: '主拱圈', sequence: 1, weight: 0.70, type: 'upper', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-002', name: '拱上结构', sequence: 2, weight: 0.20, type: 'upper', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-003', name: '桥面板', sequence: 3, weight: 0.10, type: 'upper', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },
  { id: 'ribbedArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'ribbed-arch-bridge' },

  // 箱形拱桥（box-arch-bridge）
  { id: 'boxArch-001', name: '主拱圈', sequence: 1, weight: 0.70, type: 'upper', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-002', name: '拱上结构', sequence: 2, weight: 0.20, type: 'upper', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-003', name: '桥面板', sequence: 3, weight: 0.10, type: 'upper', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'box-arch-bridge' },
  { id: 'boxArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'box-arch-bridge' },

  // 双曲拱桥（double-curved-arch-bridge）
  { id: 'doubleCurvedArch-001', name: '主拱圈', sequence: 1, weight: 0.70, type: 'upper', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-002', name: '拱上结构', sequence: 2, weight: 0.20, type: 'upper', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-003', name: '桥面板', sequence: 3, weight: 0.10, type: 'upper', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },
  { id: 'doubleCurvedArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'double-curved-arch-bridge' },

  // 刚架拱桥（rigid-frame-arch-bridge）
  { id: 'rigidFrameArch-001', name: '刚架拱片(桁架拱片)', sequence: 1, weight: 0.50, type: 'upper', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-002', name: '横向联结系', sequence: 2, weight: 0.25, type: 'upper', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-003', name: '桥面板', sequence: 3, weight: 0.25, type: 'upper', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },
  { id: 'rigidFrameArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'rigid-frame-arch-bridge' },

  // 桁架拱桥（truss-arch-bridge）
  { id: 'trussArch-001', name: '刚架拱片(桁架拱片)', sequence: 1, weight: 0.50, type: 'upper', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-002', name: '横向联结系', sequence: 2, weight: 0.25, type: 'upper', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-003', name: '桥面板', sequence: 3, weight: 0.25, type: 'upper', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-004', name: '翼墙、耳墙', sequence: 4, weight: 0.02, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-005', name: '锥坡、护坡', sequence: 5, weight: 0.01, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-006', name: '桥墩', sequence: 6, weight: 0.30, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-007', name: '桥台', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-008', name: '墩台基础', sequence: 8, weight: 0.28, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-009', name: '河床', sequence: 9, weight: 0.07, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-010', name: '调治构造物', sequence: 10, weight: 0.02, type: 'lower', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-011', name: '桥面铺装', sequence: 11, weight: 0.40, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-012', name: '伸缩缝装置', sequence: 12, weight: 0.25, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-013', name: '人行道', sequence: 13, weight: 0.10, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-014', name: '栏杆、护栏', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-015', name: '排水系统', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },
  { id: 'trussArch-016', name: '照明、标志', sequence: 16, weight: 0.05, type: 'deck', bridgeTypeId: 'truss-arch-bridge' },

  // 钢-混凝土组合拱桥（steel-concrete-composite-arch-bridge）
  { id: 'steelConcreteArch-001', name: '拱肋', sequence: 1, weight: 0.28, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-002', name: '横向联结系', sequence: 2, weight: 0.05, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-003', name: '立柱', sequence: 3, weight: 0.13, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-004', name: '吊杆', sequence: 4, weight: 0.13, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-005', name: '系杆(含锚具)', sequence: 5, weight: 0.28, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-006', name: '桥面板(梁)', sequence: 6, weight: 0.08, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-007', name: '支座', sequence: 7, weight: 0.05, type: 'upper', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-008', name: '翼墙、耳墙', sequence: 8, weight: 0.02, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-009', name: '锥坡、护坡', sequence: 9, weight: 0.01, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-010', name: '桥墩', sequence: 10, weight: 0.30, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-011', name: '桥台', sequence: 11, weight: 0.30, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-012', name: '墩台基础', sequence: 12, weight: 0.28, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-013', name: '河床', sequence: 13, weight: 0.07, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-014', name: '调治构造物', sequence: 14, weight: 0.02, type: 'lower', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-015', name: '桥面铺装', sequence: 15, weight: 0.40, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-016', name: '伸缩缝装置', sequence: 16, weight: 0.25, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-017', name: '人行道', sequence: 17, weight: 0.10, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-018', name: '栏杆、护栏', sequence: 18, weight: 0.10, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-019', name: '排水系统', sequence: 19, weight: 0.10, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },
  { id: 'steelConcreteArch-020', name: '照明、标志', sequence: 20, weight: 0.05, type: 'deck', bridgeTypeId: 'steel-concrete-composite-arch-bridge' },

  // 悬索桥（suspension-bridge）
  { id: 'suspension-001', name: '加劲梁', sequence: 1, weight: 0.15, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-002', name: '索塔', sequence: 2, weight: 0.20, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-003', name: '支座', sequence: 3, weight: 0.05, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-004', name: '主鞍', sequence: 4, weight: 0.04, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-005', name: '主缆', sequence: 5, weight: 0.25, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-006', name: '索夹', sequence: 6, weight: 0.04, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-007', name: '吊索及钢护筒', sequence: 7, weight: 0.17, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-008', name: '锚杆', sequence: 8, weight: 0.10, type: 'upper', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-009', name: '锚碇', sequence: 9, weight: 0.40, type: 'lower', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-010', name: '索塔基础', sequence: 10, weight: 0.30, type: 'lower', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-011', name: '散索鞍', sequence: 11, weight: 0.15, type: 'lower', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-012', name: '河床', sequence: 12, weight: 0.10, type: 'lower', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-013', name: '调治构造物', sequence: 13, weight: 0.05, type: 'lower', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-014', name: '桥面铺装', sequence: 14, weight: 0.40, type: 'deck', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-015', name: '伸缩缝装置', sequence: 15, weight: 0.25, type: 'deck', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-016', name: '人行道', sequence: 16, weight: 0.10, type: 'deck', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-017', name: '栏杆、护栏', sequence: 17, weight: 0.10, type: 'deck', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-018', name: '排水系统', sequence: 18, weight: 0.10, type: 'deck', bridgeTypeId: 'suspension-bridge' },
  { id: 'suspension-019', name: '照明、标志', sequence: 19, weight: 0.05, type: 'deck', bridgeTypeId: 'suspension-bridge' },

  // 斜拉桥（cable-stayed-bridge）
  { id: 'cableStayed-001', name: '斜拉索系统(斜拉索、锚具、拉索护套、减震装置等)', sequence: 1, weight: 0.40, type: 'upper', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-002', name: '主梁', sequence: 2, weight: 0.25, type: 'upper', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-003', name: '索塔', sequence: 3, weight: 0.25, type: 'upper', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-004', name: '支座', sequence: 4, weight: 0.10, type: 'upper', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-005', name: '翼墙、耳墙', sequence: 5, weight: 0.02, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-006', name: '锥坡、护坡', sequence: 6, weight: 0.01, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-007', name: '桥墩', sequence: 7, weight: 0.30, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-008', name: '桥台', sequence: 8, weight: 0.30, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-009', name: '墩台基础', sequence: 9, weight: 0.28, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-010', name: '河床', sequence: 10, weight: 0.07, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-011', name: '调治构造物', sequence: 11, weight: 0.02, type: 'lower', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-012', name: '桥面铺装', sequence: 12, weight: 0.40, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-013', name: '伸缩缝装置', sequence: 13, weight: 0.25, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-014', name: '人行道', sequence: 14, weight: 0.10, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-015', name: '栏杆、护栏', sequence: 15, weight: 0.10, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-016', name: '排水系统', sequence: 16, weight: 0.10, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
  { id: 'cableStayed-017', name: '照明、标志', sequence: 17, weight: 0.05, type: 'deck', bridgeTypeId: 'cable-stayed-bridge' },
];
