export const section_5_1 = [
  {
    id: '1',
    name: '蜂窝、麻面',
    sequence: 1,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好，无蜂窝麻面',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '较大面积蜂窝麻面',
        quantifier: '累计面积≤构件面积的 50%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '大面积蜂窝麻面',
        quantifier: '累计面积 > 构件面积的 50%',
      },
    ],
  },
  {
    id: '2',
    name: '剥落、掉角',
    sequence: 2,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好，无剥落、掉角',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '局部混凝土剥落或掉角',
        quantifier: '累计面积≤构件面积的 5%，或单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '较大范围混凝土剥落或掉角',
        quantifier: '累计面积 > 构件面积的 5% 且 <构件面积的 10%，或单处面积> 0.5m² 且 < 1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '大范围混凝土剥落或掉角',
        quantifier: '累计面积≥构件面积的 10%，或单处面积≥1.0m²',
      },
    ],
  },
  {
    id: '3',
    name: '空洞、孔洞',
    sequence: 3,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好，无空洞、孔洞',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '局部混凝土空洞、孔洞',
        quantifier: '累计面积≤构件面积的 5%，或单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '较大范围混凝土空洞、孔洞',
        quantifier: '累计面积 > 构件面积的 5% 且 <构件面积的 10%，或单处面积> 0.5m² 且 < 1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '大范围混凝土空洞、孔洞',
        quantifier: '累计面积≥构件面积的 10%，或单处面积≥1.0m²',
      },
    ],
  },
  {
    id: '4',
    name: '混凝土保护层厚度',
    sequence: 4,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '承重构件混凝土保护层厚度符合要求，对钢筋耐久性有轻度影响',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '承重构件混凝土保护层厚度不足，对钢筋耐久性有较大影响，造成钢筋锈蚀',
        quantifier: '-',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '承重构件混凝土保护层厚度严重不足，对钢筋耐久性有很大影响，钢筋失去碱性保护，发生较严重锈蚀',
        quantifier: '-',
      },
    ],
  },
  {
    id: '5',
    name: '钢筋锈蚀',
    sequence: 5,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '  5',
        qualitative: '完好',
        quantifier: '承重构件钢筋锈蚀电位水平为0~-200mV，或电阻率>20 000Ω·cm',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '承重构件有轻微锈蚀现象',
        quantifier: '承重构件钢筋锈蚀电位水平为-200~-300mV，或电阻率为15 000~20 000Ω·cm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '承重构件钢筋发生锈蚀，混凝土表面有沿钢筋的裂缝或混凝土表面有锈迹',
        quantifier: '承重构件钢筋锈蚀电位水平为-300~-400mV，或电阻率为10 000~15 000Ω·cm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '承重构件钢筋锈蚀引起混凝土剥落，钢筋裸露，表面膨胀性锈层显著',
        quantifier: '承重构件钢筋锈蚀电位水平为-400~-500mV，或电阻率为5 000~10 000Ω·cm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '承重构件大量钢筋锈蚀引起混凝土剥落，部分钢筋屈服或锈断，混凝土表面严重开裂，影响结构安全',
        quantifier: '承重构件钢筋锈蚀电位水平 < -500mV，或电阻率 <5 000Ω·cm',
      },
    ],
  },
  {
    id: '6',
    name: '混凝土碳化',
    sequence: 6,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '承重构件有少量碳化现象，且所有碳化深度均小于混凝土保护层厚度',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '承重构件的主要受力部位部分位置出现碳化现象，局部碳化深度大于混凝土保护层厚度，混凝土表面少量胶凝料松散粉化',
        quantifier: '-',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '承重构件的主要受力部位全部测点碳化且碳化深度大于混凝土保护层厚度，混凝土表面胶凝料大量松散粉化',
        quantifier: '-',
      },
    ],
  },
  {
    id: '7',
    name: '混凝土强度',
    sequence: 7,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '承重构件混凝土强度处于良好状态',
        quantifier: '承重构件混凝土推定强度均质系数K_bh≥0.95，平均强度均质系数K_bm≥1.00',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '承重构件混凝土强度处于较好状态',
        quantifier: '承重构件混凝土推定强度均质系数0.95＞K_bh≥0.90，平均强度均质系数K_bm≥0.95',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '承重构件混凝土强度处于较差状态，造成承重构件出现缺损现象',
        quantifier: '承重构件混凝土推定强度均质系数0.90＞K_bh≥0.80，平均强度均质系数K_bm≥0.90',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '承重构件混凝土强度处于很差状态，造成承重构件出现较严重缺损或变形现象',
        quantifier: '承重构件混凝土推定强度均质系数0.80＞K_bh≥0.70，平均强度均质系数K_bm≥0.85',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '7',
        qualitative: '承重构件混凝土强度处于非常差状态，造成承重构件有严重的变形、位移、失稳等现象，显著影响承载力和行车安全',
        quantifier: '承重构件混凝土推定强度均质系数K_bh＜0.70，平均强度均质系数K_bm＜0.85',
      },
    ],
  },
  {
    id: '8',
    name: '跨中挠度',
    sequence: 8,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '8',
        qualitative: '较好，梁体无明显变形',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '8',
        qualitative: '出现明显下挠，挠度小于限值，或个别构件出现弯曲变形，行车稍感振动或摇晃',
        quantifier: '跨中最大挠度≤计算跨径的1/1000；悬臂端最大挠度≤悬臂长度的1/500',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '8',
        qualitative: '出现显著下挠，挠度接近限值，或构件存在明显的永久变形，变形小于或等于规范值，梁板出现较严重病害',
        quantifier: '跨中最大挠度>计算跨径的1/1000且≤计算跨径的1/600；悬臂端最大挠度>悬臂长度的1/500且≤悬臂长度的1/300',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '8',
        qualitative: '挠度或其他变形大于限值，造成结构出现明显的永久变形，梁板出现严重病害，显著影响承载力和行车安全',
        quantifier: '跨中最大挠度>计算跨径的1/600；悬臂端最大挠度>悬臂长度的1/300',
      },
    ],
  },
  {
    id: '9',
    name: '结构变位',
    sequence: 9,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '9',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '9',
        qualitative: '较好，结构无明显位移',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '9',
        qualitative: '横向联结件松动，纵向接缝开裂较大',
        quantifier: '-',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '9',
        qualitative: '边梁有横移或外倾现象，行车振动或摇晃明显，有异常音',
        quantifier: '-',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '9',
        qualitative: '构件有严重的横向位移，存在失稳现象，结构振动或摇晃显著',
        quantifier: '-',
      },
    ],
  },
  {
    id: '10',
    name: '预应力构件损伤（锚头、钢绞线、齿板等）',
    sequence: 10,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '10',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '10',
        qualitative: '锚头、钢绞线等无明显缺陷',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '10',
        qualitative: '钢绞线裸露出现极个别断丝现象，或锚头出现开裂等现象，或齿板位置处出现部分裂缝，裂缝未超限',
        quantifier: '-',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '10',
        qualitative: '部分钢绞线断裂或失效，或锚头开裂较严重但未完全失效，或齿板位置处裂缝严重，裂缝超限',
        quantifier: '-',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '10',
        qualitative: '预应力钢绞线大量断裂，预应力损耗严重，或锚头损坏失效，梁板出现严重变形',
        quantifier: '-',
      },
    ],
  },
  {
    id: '11',
    name: '简支梁（板）桥、刚架桥裂缝',
    sequence: 11,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '11',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '11',
        qualitative: '局部出现网状裂缝，或主梁出现少量轻微裂缝，缝宽未超限',
        quantifier: '网状裂缝累计面积≤构件面积的20%，单处面积≤1.0m²，或主梁裂缝缝长≤截面尺寸的1/3',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '11',
        qualitative: '出现大面积网状裂缝，或主梁出现较多横向裂缝（钢筋混凝土梁、板），或顺主筋方向出现纵向裂缝，或出现斜裂缝、水平裂缝、竖向裂缝等，缝宽未超限',
        quantifier: '网状裂缝累计面积>构件面积的20%，单处面积>1.0m²，或主梁裂缝缝长>截面尺寸的1/3且≤截面尺寸的2/3',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '11',
        qualitative: '主梁控制截面出现较多横向裂缝（钢筋混凝土梁、板），或顺主筋方向出现严重纵向裂缝并伴有钢筋锈蚀等，或出现斜裂缝、水平裂缝、竖向裂缝等，裂缝缝宽超限',
        quantifier: '主梁裂缝缝长>截面尺寸的2/3，间距<20cm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '11',
        qualitative: '主梁控制截面出现大量结构性裂缝，裂缝大多贯通，且缝宽超限，主梁出现变形',
        quantifier: '主梁裂缝缝宽>1.0mm，间距≤10cm',
      },
    ],
  },
  {
    id: '12',
    name: '连续梁桥、连续刚构桥、悬臂梁桥、T 形刚构桥裂缝',
    sequence: 12,
    catalogId: '5-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '12',
        qualitative: '无裂缝',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '12',
        qualitative: '局部出现网状裂缝，或主梁出现少量轻微裂缝，缝宽未超限',
        quantifier: '网状裂缝累计面积≤构件面积的20%，单处面积≤1.0m²，或主梁裂缝缝长≤截面尺寸的1/3',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '12',
        qualitative: '出现大面积网状裂缝，或主梁出现横向裂缝（钢筋混凝土梁），或顺主筋方向出现纵向裂缝，或出现斜裂缝、水平裂缝、竖向裂缝等，缝宽未超限',
        quantifier: '网状裂缝累计面积>构件面积的20%，单处面积>1.0m²，或主梁缝长>截面尺寸的1/3且≤截面尺寸的1/2',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '12',
        qualitative: '主梁控制截面出现较多横向裂缝（钢筋混凝土梁），或顺主筋方向出现严重纵向裂缝并伴有钢筋锈蚀等，或出现斜裂缝、水平裂缝、竖向裂缝等，裂缝缝宽超限',
        quantifier: '主梁裂缝缝长>截面尺寸的1/2，间距<30cm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '12',
        qualitative: '主梁控制截面出现大量结构性裂缝，裂缝大多贯通，且缝宽严重超限，主梁出现变形',
        quantifier: '主梁裂缝缝宽>1.0mm，间距<20cm',
      },
    ],
  },
];
