export const section_6_1 = [
  {
    id: '1',
    name: '主拱圈变形',
    sequence: 1,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '主拱圈轻微变形',
        quantifier: '拱轴线偏离设计位置≤跨径的1/3000',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '主拱圈明显变形',
        quantifier: '拱轴线偏离设计位置>跨径的1/3000且≤跨径的1/1500',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '主拱圈严重变形',
        quantifier: '拱轴线偏离设计位置>跨径的1/1500且≤跨径的1/1000',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '主拱圈严重变形，影响结构安全',
        quantifier: '拱轴线偏离设计位置>跨径的1/1000',
      },
    ],
  },
  {
    id: '2',
    name: '主拱圈裂缝',
    sequence: 2,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好，无裂缝',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '主拱圈出现少量裂缝',
        quantifier: '裂缝宽度≤0.5mm，且长度≤构件长度的1/10',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '主拱圈出现较多裂缝',
        quantifier: '裂缝宽度>0.5mm且≤1.0mm，或长度>构件长度的1/10且≤1/5',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '主拱圈裂缝严重',
        quantifier: '裂缝宽度>1.0mm且≤2.0mm，或长度>构件长度的1/5且≤1/3',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '2',
        qualitative: '主拱圈裂缝非常严重，影响承载力',
        quantifier: '裂缝宽度>2.0mm，或长度>构件长度的1/3',
      },
    ],
  },
  {
    id: '3',
    name: '灰缝松散脱落',
    sequence: 3,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好，灰缝密实',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '局部灰缝松散、脱落',
        quantifier: '累计长度≤灰缝总长度的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '较多灰缝松散、脱落',
        quantifier: '累计长度>灰缝总长度的5%且≤15%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '大范围灰缝松散、脱落',
        quantifier: '累计长度>灰缝总长度的15%且≤30%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '灰缝严重松散脱落，砌体松动',
        quantifier: '累计长度>灰缝总长度的30%',
      },
    ],
  },
  {
    id: '4',
    name: '渗水',
    sequence: 4,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好，无渗水',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '局部轻微渗水',
        quantifier: '渗水面积≤构件面积的3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '明显渗水',
        quantifier: '渗水面积>构件面积的3%且≤10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '严重渗水',
        quantifier: '渗水面积>构件面积的10%且≤20%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '大面积严重渗水，影响结构安全',
        quantifier: '渗水面积>构件面积的20%',
      },
    ],
  },
  {
    id: '5',
    name: '砌块断裂、脱落',
    sequence: 5,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好，砌块无断裂脱落',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '个别砌块断裂或脱落',
        quantifier: '断裂或脱落砌块数量≤总数的3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '部分砌块断裂或脱落',
        quantifier: '断裂或脱落砌块数量>总数的3%且≤10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '较多砌块断裂或脱落',
        quantifier: '断裂或脱落砌块数量>总数的10%且≤20%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '大量砌块断裂脱落，影响结构稳定',
        quantifier: '断裂或脱落砌块数量>总数的20%',
      },
    ],
  },
  {
    id: '6',
    name: '风化',
    sequence: 6,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好，无风化',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '表面轻微风化',
        quantifier: '风化深度≤10mm，面积≤构件面积的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '明显风化',
        quantifier: '风化深度>10mm且≤30mm，或面积>构件面积的10%且≤30%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '严重风化',
        quantifier: '风化深度>30mm且≤50mm，或面积>构件面积的30%且≤50%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '6',
        qualitative: '非常严重风化，影响承载力',
        quantifier: '风化深度>50mm，或面积>构件面积的50%',
      },
    ],
  },
  {
    id: '7',
    name: '拱脚位移',
    sequence: 7,
    catalogId: '6-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好，无位移',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '拱脚轻微位移',
        quantifier: '水平位移≤10mm，竖向位移≤5mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '拱脚明显位移',
        quantifier: '水平位移>10mm且≤30mm，或竖向位移>5mm且≤15mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '拱脚严重位移',
        quantifier: '水平位移>30mm且≤50mm，或竖向位移>15mm且≤25mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '7',
        qualitative: '拱脚非常严重位移，影响结构安全',
        quantifier: '水平位移>50mm，或竖向位移>25mm',
      },
    ],
  },
];
