export const section_7_7 = [
  {
    id: '1',
    name: '锚坑漏水',
    sequence: 1,
    catalogId: '7-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '锚坑内无渗漏水现象',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '锚坑有明显渗漏水现象',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '锚坑漏水较严重,伴有锈蚀现象',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '锚坑渗漏水严重,多处锈蚀',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '顶板、侧墙损坏',
    sequence: 2,
    catalogId: '7-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '顶板、侧墙表面状况完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '顶板、侧墙有局部麻面沉积物',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '顶板、侧墙出现锈迹、蜂窝、渗出物，伴有细微裂缝',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '顶板及侧墙出现大面积锈迹，混凝土剥落，钢筋外露锈蚀，有较大裂缝',
        quantifier: '',
      },
    ],
  },
  {
    id: '3',
    name: '锚碇均匀沉降',
    sequence: 3,
    catalogId: '7-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '锚碇无沉降',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '锚碇有轻微沉降',
        quantifier: '沉降≤10mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '锚碇沉降较严重',
        quantifier: '沉降>10mm且≤50mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '锚碇沉降严重',
        quantifier: '沉降>50mm',
      },
    ],
  },
  {
    id: '4',
    name: '表观病害',
    sequence: 4,
    catalogId: '7-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '锚碇个别部位出现明显表观病害如裂缝、剥落、露筋、钢筋锈蚀、空洞等',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '锚碇外观有较多表观病害且情况严重,如裂缝、剥落、露筋、钢筋锈蚀、空洞等,不符合相关规范要求',
        quantifier: '',
      },
    ],
  },
  {
    id: '5',
    name: '水平位移',
    sequence: 5,
    catalogId: '7-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '有水平位移',
        quantifier: '',
      },
    ],
  },
];
