export const section_8_4 = [
  {
    id: '1',
    name: '倾斜变形',
    sequence: 1,
    catalogId: '8-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '无倾斜变形',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '有倾斜变形现象或存在扭转现象,但情况较轻微,不影响结构安全',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '存在倾斜变形或存在扭转,两塔不对称变位,存在安全隐患',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '索塔出现明显倾斜,或两塔不对称变位严重,造成主梁出现严重变形,严重影响结构安全',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '裂缝',
    sequence: 2,
    catalogId: '8-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好,无裂缝',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '网状裂缝:局部网状裂缝;其他裂缝:有少量裂缝,缝宽未超限',
        quantifier: '网状裂缝:累计面积≤构件面积的20%,单处面积≤1.0m²;其他裂缝:缝长≤截面尺寸的1/3',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '网状裂缝:局部网状裂缝;其他裂缝:有大量裂缝,缝宽未超限',
        quantifier: '网状裂缝:累计面积>构件面积的20%,单处面积>1.0m²;其他裂缝:缝长>截面尺寸的1/3且≤截面尺寸的2/3,间距≥20cm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '有大量裂缝,缝宽超限',
        quantifier: '缝宽>限值,缝长>截面尺寸的2/3,间距<20cm',
      },
    ],
  },
  {
    id: '3',
    name: '沉降',
    sequence: 3,
    catalogId: '8-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '索塔有小幅度沉降,但沉降稳定',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '索塔沉降较大,但沉降稳定',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '索塔沉降量异常且不稳定,或索塔基础出现严重沉降或位移',
        quantifier: '',
      },
    ],
  },
  {
    id: '4',
    name: '锚固区渗水',
    sequence: 4,
    catalogId: '8-4-4',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '锚固区有轻微渗水',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '锚固区有局部明显渗水,渗水量较大',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '锚固区多处有明显渗水,渗水量大;个别渗水处伴有晶体析出或锈蚀,流膏处混凝土松散',
        quantifier: '',
      },
    ],
  },
  {
    id: '5',
    name: '蜂窝、麻面',
    sequence: 5,
    catalogId: '8-4-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '依照表7.5.1-2标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '6',
    name: '剥落、露筋',
    sequence: 6,
    catalogId: '8-4-6',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '依照表7.5.1-3标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '钢筋锈蚀',
    sequence: 7,
    catalogId: '8-4-7',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '依照表7.5.1-4标准评定',
        quantifier: '',
      },
    ],
  },
];
