export const section_7_8 = [
  {
    id: '1',
    name: '掉皮',
    sequence: 1,
    catalogId: '7-8',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '较小范围涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计面积≤构件面积的10%,单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '较大范围涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计面积>构件面积的10%且≤构件面积的20%,单处面积>0.5m²且≤1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '大范围涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计面积>构件面积的20%,单处面积>1.0m²',
      },
    ],
  },
  {
    id: '2',
    name: '锈蚀',
    sequence: 2,
    catalogId: '7-8',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '构件表面有轻微锈蚀,但无可见油脂和污垢,且没有附着不牢的氧化皮、铁锈和油漆层',
        quantifier: '锈蚀面积≤构件面积的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '构件表面锈蚀,且部分氧化皮或油漆层剥落,个别有明显变位',
        quantifier: '锈蚀面积>构件面积的5%且≤构件面积的10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '构件严重锈蚀,个别板件锈穿极易撕裂,氧化皮或油漆层因锈蚀而部分剥落或者可以刮除',
        quantifier: '锈蚀面积>构件面积的10%',
      },
    ],
  },
  {
    id: '3',
    name: '裂纹',
    sequence: 3,
    catalogId: '7-8',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '锚杆存在轻微裂纹,但符合相关规范要求',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '锚杆有较多裂纹,不符合相关规范要求,局部有锈蚀现象',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '锚杆外观有大量裂纹,个别部位裂纹超限,不符合相关规范要求,锈蚀现象严重,严重影响结构安全',
        quantifier: '',
      },
    ],
  },
];
