export const section_7_4_1 = [
  {
    id: '1',
    name: '剥落、露筋',
    sequence: 1,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '局部混凝土剥落或露筋',
        quantifier: '累计面积≤构件面积的3%，单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '较大范围混凝土剥落或露筋',
        quantifier: '累计面积>构件面积的3%且≤构件面积的10%，单处面积≤0.5m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '大范围混凝土剥落或露筋',
        quantifier: '累计面积>构件面积的10%，单处面积>0.5m²',
      },
    ],
  },
  {
    id: '2',
    name: '跨中挠度',
    sequence: 2,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '挠度未大于限值',
        quantifier: '跨中最大挠度<计算跨径的1/800',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '挠度接近限值,主梁有明显变形,影响结构安全',
        quantifier: '跨中最大挠度≥计算跨径的1/800且≤计算跨径的1/500',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '2',
        qualitative: '主梁严重变形,挠度大于限值,梁板出现严重病害,有不正常移动并影响结构安全',
        quantifier: '跨中最大挠度>计算跨径的1/500',
      },
    ],
  },
  {
    id: '3',
    name: '构件变形',
    sequence: 3,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '加劲梁横隔板等次要构件出现弯曲变形',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '加劲梁出现异常弯曲变形或线形明显变化,行车振动或摇晃明显或有异常音',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '加劲梁出现严重变形,导致梁板出现严重病害,显著影响承载力,结构振动或摇晃显著,有不正常移动',
        quantifier: '',
      },
    ],
  },
  {
    id: '4',
    name: '混凝土裂缝',
    sequence: 4,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好,无裂缝',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '网状裂缝:局部网状开裂\n竖向裂缝:少量裂缝,缝宽未超限\n纵向裂缝:结合面开裂或有其他纵向裂缝\n斜裂缝:少量裂缝,缝宽未超限',
        quantifier: '网状裂缝:累计面积≤构件面积的20%,单处面积≤0.5m²\n竖向裂缝:缝长≤截面尺寸的1/3\n纵向裂缝:缝长≤结合面长度或跨长的1/8\n斜裂缝:缝长≤截面尺寸的1/3',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '网状裂缝:局部网状开裂\n竖向裂缝:较多裂缝,缝宽未超限\n纵向裂缝:结合面开裂或有纵向裂缝\n斜裂缝:较多裂缝,缝宽未超限',
        quantifier: '网状裂缝:累计面积>构件面积的20%,单处面积>0.5m²\n竖向裂缝:缝长>截面尺寸的1/3且≤截面尺寸的1/2,间距≥30cm\n纵向裂缝:缝长>结合面长度或跨长的1/8且≤结合面长度或跨长的1/2\n斜裂缝:缝长>截面尺寸的1/3且≤截面尺寸的2/3',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '竖向裂缝:主梁控制截面出现大量裂缝,缝宽超限\n纵向裂缝:存在严重结合面开裂现象或有大量纵向裂缝\n斜裂缝:主梁控制截面出现大量裂缝,缝宽超限值',
        quantifier: '竖向裂缝:缝长>截面尺寸的1/2,缝宽>限值,间距<30cm\n纵向裂缝:缝长>结合面长或跨长的1/2\n斜裂缝:缝长>截面尺寸的2/3,缝宽>限值',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '竖向裂缝:主梁控制截面出现大量裂缝,裂缝大多贯通且缝宽超限,主梁出现严重变形\n斜裂缝:主梁控制截面出现大量裂缝且缝宽超限,主梁出现严重变形',
        quantifier: '竖向裂缝:缝长>截面尺寸的1/2,缝宽>1.0mm,间距<10cm\n斜裂缝:缝长>截面尺寸的2/3,缝宽>1.0mm',
      },
    ],
  },
  {
    id: '5',
    name: '蜂窝、麻面',
    sequence: 5,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '参照表5.1.1-1标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '6',
    name: '剥落、掉角',
    sequence: 6,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '参照表5.1.1-2标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '空洞、孔洞',
    sequence: 7,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '参照表5.1.1-3标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '8',
    name: '混凝土保护层厚度',
    sequence: 8,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '参照表5.1.1-4标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '9',
    name: '钢筋锈蚀',
    sequence: 9,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '9',
        qualitative: '参照表5.1.1-5标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '10',
    name: '混凝土碳化',
    sequence: 10,
    catalogId: '7-4-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '10',
        qualitative: '参照表5.1.1-6标准评定',
        quantifier: '',
      },
    ],
  },
];

export const section_7_4_2 = [
  {
    id: '1',
    name: '构件变形',
    sequence: 1,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '-',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '构件轻微变形',
        quantifier: '压力杆件弯曲矢度≤杆件自由长度的1/1500,或拉力杆件弯曲矢度≤杆件自由长度的1/800,或腹杆、连接杆件弯曲矢度≤杆件自由长度的1/500',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '构件明显变形',
        quantifier: '压力杆件弯曲矢度>杆件自由长度的1/1500且≤杆件自由长度的1/1000,或拉力杆件弯曲矢度>杆件自由长度的1/800且≤杆件自由长度的1/500,或腹杆、连接杆件弯曲矢度>杆件自由长度的1/500且≤杆件自由长度的1/300',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '构件严重变形,存在失稳现象,结构振动或摇晃显著',
        quantifier: '压力杆件弯曲矢度>杆件自由长度的1/1000,或拉力杆件弯曲矢度>杆件自由长度的1/500,或腹杆、连接杆件弯曲矢度>杆件自由长度的1/300',
      },
    ],
  },
  {
    id: '2',
    name: '锈蚀',
    sequence: 2,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '构件表面少量锈蚀,部分氧化皮或油漆层剥落',
        quantifier: '锈蚀累计面积≤构件面积的3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '构件表面有大量点蚀现象,氧化皮或油漆层因锈蚀而部分剥落或者可以刮除',
        quantifier: '锈蚀累计面积>构件面积的3%且≤构件面积的5%,或锈蚀孔洞≤2个,孔洞直径≤30mm且≤杆件宽度的15%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '构件表面有严重点蚀现象,氧化皮或油漆层因锈蚀而全面剥离,较多部位被锈蚀成洞,影响结构安全',
        quantifier: '锈蚀累计面积>构件面积的5%,或锈蚀孔洞>2个,孔洞直径>30mm且>杆件宽度的15%',
      },
    ],
  },
  {
    id: '3',
    name: '跨中挠度',
    sequence: 3,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '挠度未大于限值',
        quantifier: '跨中最大挠度≤计算跨径的1/1200',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '挠度接近限值',
        quantifier: '跨中最大挠度>计算跨径的1/1200且≤计算跨径的1/800',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '主梁严重变形,挠度超出限值,有不正常移动,影响结构安全',
        quantifier: '跨中最大挠度>计算跨径的1/800',
      },
    ],
  },
  {
    id: '4',
    name: '裂缝',
    sequence: 4,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '钢构件出现极少量细小裂纹',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '钢构件出现较多细小裂缝,截面削弱',
        quantifier: '受拉翼缘焊接盖板端部裂缝长度≤10mm,或桁梁端横梁与纵梁连接处下端处裂缝长度≤20mm,或主桁腹杆铆接、栓接头处裂缝长度≤20mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '钢构件出现较多裂缝,截面削弱',
        quantifier: '受拉翼缘焊接盖板端部裂缝长度>10mm且≤20mm,或桁梁端横梁与纵梁连接处下端处裂缝长度>20mm且≤50mm,或主桁腹杆铆接、栓接头处裂缝长度>20mm且≤50mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '钢构件严重裂缝,主梁变形,造成严重安全隐患',
        quantifier: '受拉翼缘焊接盖板端部裂缝长度>20mm,或桁梁端横梁与纵梁连接处下端处裂缝长度>50mm,或主桁腹杆铆接、栓接头处裂缝长度>50mm',
      },
    ],
  },
  {
    id: '5',
    name: '涂层劣化',
    sequence: 5,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '参照表5.2.1-1标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '6',
    name: '焊缝开裂',
    sequence: 6,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '参照表5.2.1-3标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '铆钉(螺栓)损失',
    sequence: 7,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '参照表5.2.1-4标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '8',
    name: '结构变位',
    sequence: 8,
    catalogId: '7-4-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '参照表5.2.1-8标准评定',
        quantifier: '',
      },
    ],
  },
];

export const section_7_4_3 = [
  {
    id: '1',
    name: '构件变形',
    sequence: 1,
    catalogId: '7-4-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '钢构件轻微变形',
        quantifier: '钢材料构件竖向弯曲矢度≤跨度的1/1500,或钢材料纵梁、横梁横向弯曲矢度≤杆件自由长度的1/8000',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '钢构件明显变形',
        quantifier: '钢材料构件竖向弯曲矢度>跨度的1/1500且≤跨度的1/1000,或钢材料纵梁、横梁横向弯曲矢度>杆件自由长度的1/8000且≤杆件自由长度的1/5000',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '钢构件严重变形,结构振动或摇晃显著,有不正常移动',
        quantifier: '钢材料构件竖向弯曲矢度>跨度的1/1000,或钢材料纵梁、横梁横向弯曲矢度>杆件自由长度的1/5000',
      },
    ],
  },
  {
    id: '2',
    name: '锈蚀',
    sequence: 2,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '构件表面锈蚀,且部分氧化皮或油漆层剥落',
        quantifier: '锈蚀累计面积≤构件面积的2%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '构件表面有较多点蚀现象,氧化皮或油漆层因锈蚀而部分剥落或者可以刮除,出现锈蚀成洞现象',
        quantifier: '锈蚀累计面积>构件面积的2%且≤构件面积的5%,或锈蚀孔洞≤2个,孔洞直径≤30mm,边缘完好,或腹板、横隔板洞孔直径≤50mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '构件表面有严重的点蚀现象,氧化皮或油漆层因锈蚀而全面剥离,较多部位被锈蚀成洞,影响构件安全',
        quantifier: '锈蚀累计面积>构件面积的5%,或锈蚀孔洞>2个,孔洞直径>30mm,或腹板、横隔板孔洞直径>50mm',
      },
    ],
  },
  {
    id: '3',
    name: '跨中挠度',
    sequence: 3,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '-',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '跨中挠度未大于限值',
        quantifier: '跨中最大挠度≤计算跨径的1/600',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '跨中挠度大于限值',
        quantifier: '跨中最大挠度>计算跨径的1/600且≤计算跨径的1/400',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '跨中挠度大于限值,主梁严重变形,梁体出现严重病害,有不正常移动并影响结构安全',
        quantifier: '跨中最大挠度>计算跨径的1/400',
      },
    ],
  },
  {
    id: '4',
    name: '裂缝',
    sequence: 4,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '钢构件出现极少量细小裂纹',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '钢构件出现较多细小裂缝,截面削弱',
        quantifier: '加劲梁、纵横梁受拉翼缘边裂缝长度≤3mm,或受拉翼缘焊接盖板端部裂缝长度≤10mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '钢构件出现较多裂缝,截面削弱',
        quantifier: '加劲梁、纵横梁受拉翼缘边裂缝长度>3mm且≤5mm,或受拉翼缘焊接盖板端部裂缝长度>10mm且≤20mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '钢构件严重裂缝,主梁变形,截面削弱,造成严重安全隐患',
        quantifier: '加劲梁、纵横梁受拉翼缘边裂缝长度>5mm,或受拉翼缘焊接盖板端部裂缝长度>20mm',
      },
    ],
  },
  {
    id: '5',
    name: '涂层劣化',
    sequence: 5,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '参照表5.2.1-1标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '6',
    name: '焊缝开裂',
    sequence: 6,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '参照表5.2.1-3标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '铆钉(螺栓)损失',
    sequence: 7,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '参照表5.2.1-4标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '8',
    name: '结构变位',
    sequence: 8,
    catalogId: '7-4-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '参照表5.2.1-8标准评定',
        quantifier: '',
      },
    ],
  },
];

export const section_7_4 = [
  ...section_7_4_1,
  ...section_7_4_2,
  ...section_7_4_3,
];
