export const section_7_3 = [
  {
    id: '1',
    name: '渗水',
    sequence: 1,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '有轻微渗水现象',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '个别构件防水渗透装置损坏,明显渗水,构件有锈蚀现象',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '较多构件防水渗透装置损坏,多处构件明显渗水,构件渗水处伴有较严重锈蚀现象',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '锈蚀、腐蚀',
    sequence: 2,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '表面有少量油脂和污垢,没有附着不牢的氧化皮、铁锈和油漆层,或表面有少量点蚀、锈斑,或镀锌钢丝出现锌腐蚀亮斑',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '表面普遍有点蚀、锈斑、锈坑,或氧化皮、油漆层因锈蚀而部分剥落或者可以刮除,或钢丝发生较严重锈蚀,或镀锌钢丝锌层出现铁腐蚀斑点和腐坑',
        quantifier: '锈蚀面积≤构件面积5%,或构件表面锈蚀孔洞≤2个',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '表面普遍有点蚀现象,氧化皮或油漆层因锈蚀而全面剥离,或钢丝发生较严重锈蚀并有部分断裂,或镀锌钢丝严重腐蚀有开裂现象',
        quantifier: '锈蚀面积>构件面积5%,或构件表面锈蚀孔洞>2个',
      },
    ],
  },
  {
    id: '3',
    name: '锚头损坏',
    sequence: 3,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '个别锚头轻微破损',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '个别锚头破损、松动',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '较多锚头破损、松动或裂缝,个别冷铸锚头破损严重或裂缝超限,严重影响构件安全',
        quantifier: '',
      },
    ],
  },
  {
    id: '4',
    name: '橡胶老化变质',
    sequence: 4,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '吊索端部及减振器橡胶轻微老化',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '吊索端部及减振器橡胶老化、轻微开裂',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '吊索端部及减振器橡胶老化、开裂严重',
        quantifier: '',
      },
    ],
  },
  {
    id: '5',
    name: '掉漆、起皮',
    sequence: 5,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '吊索表面局部面漆变色、起泡',
        quantifier: '累计面积≤构件面积的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '吊索表面较大范围面漆轻微起皮、起泡或剥落',
        quantifier: '累计面积>构件面积的5%且≤构件面积的15%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '吊索表面较大范围面漆起皮、起泡或剥落',
        quantifier: '累计面积>构件面积的15%',
      },
    ],
  },
  {
    id: '6',
    name: '防护套破坏',
    sequence: 6,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '个别防护套及连接处轻微松动',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '部分防护套以及连接处松动或套管顶没有密封',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '较多防护套以及连接处松动或套管顶没有密封,局部造成渗水',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '吊索的防护层破坏',
    sequence: 7,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '个别吊索防护层轻微老化或破损',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '个别吊索防护层老化、破损、裂纹',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '吊索防护层老化、破损、裂纹或积水,造成局部渗水或锈蚀并伴有钢丝严重锈蚀现象',
        quantifier: '',
      },
    ],
  },
  {
    id: '8',
    name: '钢丝断丝',
    sequence: 8,
    catalogId: '7-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '8',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '8',
        qualitative: '钢丝少量锈蚀,无断丝',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '8',
        qualitative: '钢丝锈蚀,防腐层有大量麻坑,甚至出现断丝',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '8',
        qualitative: '吊索钢丝大量严重锈蚀或损坏,钢丝断裂,甚至主梁出现变形,造成安全隐患',
        quantifier: '',
      },
    ],
  },
];
