export const section_7_5 = [
  {
    id: '1',
    name: '倾斜变形',
    sequence: 1,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '有倾斜变形现象或存在扭转现象,但较轻微,不影响结构安全',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '有较大倾斜变形或存在明显扭转,造成安全隐患',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '索塔出现严重倾斜变形,塔根明显裂缝,塔顶偏移超过限值,严重影响结构安全',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '蜂窝、麻面',
    sequence: 2,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '局部蜂窝麻面',
        quantifier: '累计面积≤构件面积的20%,单处面积≤3.0m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '大面积蜂窝麻面',
        quantifier: '累计面积>构件面积的20%,单处面积>3.0m²',
      },
    ],
  },
  {
    id: '3',
    name: '剥落、露筋',
    sequence: 3,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '局部混凝土剥落或露筋',
        quantifier: '累计面积≤构件面积的3%,单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '较大范围混凝土剥落或露筋',
        quantifier: '累计面积>构件面积的3%且≤构件面积的10%,单处面积>0.5m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '大范围混凝土剥落或露筋',
        quantifier: '累计面积>构件面积的10%,单处面积>0.5m²',
      },
    ],
  },
  {
    id: '4',
    name: '钢筋锈蚀',
    sequence: 4,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好,无锈蚀现象',
        quantifier: '钢筋锈蚀电位水平≤0mV且≥-200mV; 或电阻率>20000Ω·cm',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '有锈蚀现象,混凝土表面有沿钢筋的裂缝或混凝土表面有锈迹',
        quantifier: '钢筋锈蚀电位水平<-200mV且≥-400mV; 或电阻率≥10000Ω·cm且≤20000Ω·cm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '钢筋锈蚀,主筋锈蚀或混凝土表面保护层剥落',
        quantifier: '钢筋锈蚀电位水平<-400mV且≥-500mV; 或电阻率≥5000Ω·cm且<10000Ω·cm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '钢筋严重锈蚀,混凝土表面开裂严重',
        quantifier: '钢筋锈蚀电位水平为<-500mV; 或电阻率<5000Ω·cm',
      },
    ],
  },
  {
    id: '5',
    name: '混凝土裂缝',
    sequence: 5,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好,无裂缝',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '网状裂缝:局部网状裂缝',
        quantifier: '网状裂缝:累计面积≤构件面积的20%,单处面积≤1.0m²',
      },
      {
        id: '3',
        scale: 2,
        indicatorId: '5',
        qualitative: '其他裂缝:有少量裂缝,缝宽未超限',
        quantifier: '其他裂缝:缝长≤截面尺寸的1/3',
      },
      {
        id: '4',
        scale: 3,
        indicatorId: '5',
        qualitative: '网状裂缝:局部网状裂缝',
        quantifier: '网状裂缝:累计面积>构件面积的20%,单处面积>1.0m²',
      },
      {
        id: '5',
        scale: 3,
        indicatorId: '5',
        qualitative: '其他裂缝:有大量裂缝,缝宽未超限',
        quantifier: '其他裂缝:缝长>截面尺寸的1/3且≤截面尺寸的2/3,间距≥20cm',
      },
      {
        id: '6',
        scale: 4,
        indicatorId: '5',
        qualitative: '有大量裂缝,裂缝缝宽超限',
        quantifier: '缝宽>限值,缝长>截面尺寸的2/3,间距<20cm',
      },
    ],
  },
  {
    id: '6',
    name: '沉降',
    sequence: 6,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '索塔有轻微沉降,但沉降稳定',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '索塔有小幅度沉降,但沉降稳定',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '索塔沉降较大,但沉降稳定',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '6',
        qualitative: '索塔或索塔基础出现严重不均匀沉降或位移,影响结构安全',
        quantifier: '',
      },
    ],
  },
  {
    id: '7',
    name: '基础冲刷',
    sequence: 7,
    catalogId: '7-5',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '基础基本无局部冲刷现象',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '基础出现局部冲刷现象,程度较轻',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '基础出现较严重局部冲刷现象',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '7',
        qualitative: '基础出现严重局部冲刷现象,基础不稳定,出现严重滑动、下沉、位移、倾斜等现象',
        quantifier: '',
      },
    ],
  },
];
