export const section_5_3_1 = [
  {
    id: '1',
    name: ' 板式支座老化变质、开裂 ',
    sequence: 1,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '轻微老化,表面有脏污,出现裂缝',
        quantifier: '裂缝宽度≤1.0mm,裂缝长度>相应边长10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '橡胶支座老化变形,裂缝较严重',
        quantifier: '裂缝宽度>1mm且≤2mm,裂缝长度>相应边长的25%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '橡胶支座老化破裂,裂缝严重,且造成其他构件产生较严重病害',
        quantifier: '裂缝宽度>2mm,裂缝长度>相应边长的25%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '橡胶支座老化破裂,裂缝非常严重,已经失去正常支承功能,且使相关上下部结构受到异常约束,造成严重损坏,主梁出现严重变形',
        quantifier: '裂缝宽度>2mm,裂缝长度>相应边长的50%',
      },
    ],
  },
  {
    id: '2',
    name: ' 板式支座缺陷 ',
    sequence: 2,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '有外鼓现象',
        quantifier: '沿支座一侧外鼓长度≤相应边长的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '外鼓现象较严重，或钢板局部外露',
        quantifier: '沿支座一侧外鼓长度>相应边长的10%且≤相应边长的25%，或钢板外露长度>100mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '外鼓现象严重，或钢板大部分外露',
        quantifier: '沿支座一侧外鼓长度>相应边长的25%，或钢板外露长度>100mm',
      },
    ],
  },
  {
    id: '3',
    name: ' 板式支座位置串动、脱空或剪切超限 ',
    sequence: 3,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '支座出现剪切变形或位置略有偏移',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '支座出现剪切变形或位置有较大偏移',
        quantifier: '剪切角度≤45°',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '支座串动较严重，或出现脱空现象，或出现严重变形',
        quantifier: '串动长度≤相应边长的25%，或剪切角度>45°且≤60°',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '串动严重并造成桥梁其他构件出现较严重病害',
        quantifier: '串动长度>相应边长的25%',
      },
      {
        id: '6',
        scale: 5,
        indicatorId: '3',
        qualitative: '支座错位、串动、变形严重，已经失去正常支承功能，造成相关上下部结构严重损坏，主梁出现严重变形',
        quantifier: '剪切角度>60°',
      },
    ],
  },
  {
    id: '4',
    name: ' 盆式支座组件损坏 ',
    sequence: 4,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '盆底四角翘起，或钢盆出现较多锈蚀，或支底底板局部裂纹、掉角',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '钢件非主要受力部位出现脱焊，或钢盆出现较多锈蚀并伴有剥落，或除盆底、盆环外其他部位开裂，或底板产生变形，混凝土酥裂，露筋、掉角',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '大量锚栓剪断，或底板变形，大部分压碎、剥离，造成相关上下部结构受到异常约束，损坏严重',
        quantifier: '锚栓剪断≤50%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '有大量的锚栓剪断或盆环开裂、脱焊，支座破损、缺失严重，已经失去正常支承功能，造成相关上下部结构严重损坏，主梁出现严重变形',
        quantifier: '锚栓剪断>50%',
      },
    ],
  },
  {
    id: '5',
    name: ' 聚四氟乙烯滑板磨损 ',
    sequence: 5,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '磨损较少',
        quantifier: '聚四氟乙烯滑板外露高度≥0.5mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '磨损较多',
        quantifier: '聚四氟乙烯滑板外露高度≥0.2mm且<0.5mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '磨损严重，并造成其他构件出现病害',
        quantifier: '聚四氟乙烯滑板外露高度<0.2mm',
      },
    ],
  },
  {
    id: '6',
    name: ' 盆式支座位移、转角超限 ',
    sequence: 6,
    catalogId: '5-3-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '有位移现象，或有较大转角，转角超出设计值',
        quantifier: '位移≤10mm，或转角≤设计转角20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '位移现象较明显，或有很大转角，转角远超出设计值',
        quantifier: '位移>10mm，或转角>设计转角20%',
      },
    ],
  },
];

export const section_5_3_2 = [
  {
    id: '1',
    name: '钢支座组件或功能缺陷',
    sequence: 1,
    catalogId: '5-3-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '有锈蚀现象；或牙板咬死；或个别锚栓出现剪断现象；或底板与垫石没有密贴，出现较大缝隙',
        quantifier: '锚栓剪断数量≤5%；或底板与垫石间缝隙宽度≤2.0mm，深度>50mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '大部分有锈蚀现象，并有剥落，或非主要受力部件出现脱焊；或牙板折断，辊轴连杆螺丝剪断；或锚栓剪断数量较多，螺杆松动；或底板与垫石没有密贴，出现很大的缝隙，出现翻浆、积水',
        quantifier: '锚栓剪断数量>5%且≤30%；或底板与垫石缝隙宽度>2.0mm，深度≥支座相应边长的25%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '主要受力部件脱焊；或支座不能活动；或大量锚钉或锚栓剪断；或垫石出现严重裂损',
        quantifier: '锚钉或锚栓剪断数量>30%',
      },
    ],
  },
  {
    id: '2',
    name: '钢支座位移、转角超限',
    sequence: 2,
    catalogId: '5-3-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '位移大于限值',
        quantifier: '纵向位移≤5mm，或横向位移≤2mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '位移大于限值严重，或倾斜度超标',
        quantifier: '纵向位移>5mm，或横向位移>2mm',
      },
    ],
  },
  {
    id: '3',
    name: '钢支座部件磨损、裂缝',
    sequence: 3,
    catalogId: '5-3-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '钢部件磨损出现凹陷，或出现微裂缝',
        quantifier: '磨损凹陷≤1.0mm，或裂缝深度≤5.0mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '钢部件磨损出现凹陷，或出现较大裂缝',
        quantifier: '磨损凹陷>1.0mm且≤3.0mm，或裂缝深度>5.0mm且≤10.0mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '钢部件磨损出现严重凹陷，或出现较严重裂缝',
        quantifier: '磨损凹陷>3.0mm，或裂缝深度>10.0mm',
      },
    ],
  },
];

export const section_5_3_3 = [
  {
    id: '1',
    name: '混凝土缺损',
    sequence: 1,
    catalogId: '5-3-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '局部混凝土脱皮、露筋、裂纹、剥离、掉角',
        quantifier: '累计面积≤构件面积的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '较大范围混凝土脱皮、露筋、酥裂',
        quantifier: '累计面积>构件面积的5%且≤构件面积的20%，或单处面积≤1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '大范围混凝土脱皮、露筋、压碎',
        quantifier: '累计面积>构件面积的20%',
      },
    ],
  },
  {
    id: '2',
    name: '活动支座滑动面不平整、生锈咬死',
    sequence: 2,
    catalogId: '5-3-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '滑动面不平整、出现生锈现象',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '滑动面不平整、生锈咬死，支座不活动',
        quantifier: '',
      },
    ],
  },
  {
    id: '3',
    name: '轴承有裂纹、切口或偏移',
    sequence: 3,
    catalogId: '5-3-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '轴承有裂纹、切口或偏移，影响了活动能力',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '轴承有裂纹、切口或偏移，失去了活动能力',
        quantifier: '',
      },
    ],
  },
];

export const section_5_3_4 = [
  {
    id: '1',
    name: '螺纹、螺帽松动或锚螺杆剪切',
    sequence: 1,
    catalogId: '5-3-4',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '个别螺纹、螺帽轻微松动，或个别锚螺杆出现轻微剪切变形',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '螺纹、螺帽出现松动，个别出现脱落，或锚螺杆出现剪切变形甚至剪断',
        quantifier: '螺纹、螺帽松动数量≤3%，或锚螺杆剪切变形数量≤10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '螺纹、螺帽出现松动、脱落甚至个别出现断裂，或锚螺杆出现剪切变形、剪断现象，并且造成相关上下部结构受到异常约束，出现损坏',
        quantifier: '螺纹、螺帽出现松动、脱落甚至断裂的数量>3%且≤10%，或锚螺杆出现剪切变形数量>10%且≤20%，锚螺杆剪断数量≤10%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '螺纹、螺帽松动、脱落、断裂现象，或锚螺杆出现剪切变形、剪断现象，支座已经失去正常支承功能，并且造成相关上下部结构受到异常约束，严重损坏，主梁出现严重变形或挠度大于限值',
        quantifier: '螺纹、螺帽出现松动、脱落甚至断裂的数量>10%，或锚螺杆出现剪切变形数量>20%，锚螺杆剪断数量>10%',
      },
    ],
  },
  {
    id: '2',
    name: '上下座板（盆）锈蚀',
    sequence: 2,
    catalogId: '5-3-4',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '局部出现锈蚀',
        quantifier: '锈蚀面积≤5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '出现锈蚀，个别位置有剥落',
        quantifier: '锈蚀面积>5%且≤20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '出现锈蚀，大多数位置有剥落',
        quantifier: '锈蚀面积>20%',
      },
    ],
  },
  {
    id: '3',
    name: '纵横线扭转',
    sequence: 3,
    catalogId: '5-3-4',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '纵横线发生轻微扭转',
        quantifier: '纵横线扭转≤1.0mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '纵横线发生较大扭转',
        quantifier: '纵横线扭转>1.0mm',
      },
    ],
  },
];

export const section_5_3 = [
  ...section_5_3_1,
  ...section_5_3_2,
  ...section_5_3_3,
  ...section_5_3_4,
];
