export const section_6_2 = [
  {
    id: '1',
    name: '实腹拱的侧墙与主拱圈脱裂',
    sequence: 1,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '个别位置出现脱裂，缝宽较小且不连续',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '侧墙与主拱圈间较大范围出现断裂、脱开，且断裂脱开连续',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '侧墙与主拱圈间大范围出现断裂、脱开，且断裂脱开连续，造成桥面变形',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '侧墙与主拱圈间严重脱裂，造成桥面板严重塌落或结构和桥面变形过大，严重影响结构安全',
        quantifier: '—',
      },
    ],
  },
  {
    id: '2',
    name: '实腹拱的侧墙变形、位移',
    sequence: 2,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '-',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '侧墙出现鼓肚现象',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '侧墙出现倾斜、外移等变形现象，填料或桥面出现沉陷',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '2',
        qualitative: '侧墙产生严重倾斜、外移、鼓肚等现象，导致桥面出现严重塌陷或沉降，不能正常行车',
        quantifier: '—',
      },
    ],
  },
  {
    id: '3',
    name: '实腹拱的拱上填料沉陷或开裂',
    sequence: 3,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '拱上填料出现轻微沉陷或开裂',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '拱上填料出现明显沉陷或开裂，但变形不影响正常行车',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '拱上填料出现较大范围沉陷或开裂，导致桥面出现塌陷或沉降',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
  {
    id: '4',
    name: '空腹拱的腹拱或横向联结系变形、错位',
    sequence: 4,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '-',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '个别腹拱或横向联结系出现变形、错位，但不影响行车',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '较多腹拱或横向联结系出现变形、错位，影响正常行车',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '腹拱或横向联结系产生严重变形、错位，导致桥面出现严重塌陷或沉降，变形过大，不能正常行车',
        quantifier: '—',
      },
    ],
  },
  {
    id: '5',
    name: '立墙或立柱倾斜、开裂或脱落',
    sequence: 5,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '个别立墙或立柱出现倾斜、开裂甚至脱落',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '较多立墙或立柱出现倾斜，或大范围出现开裂、脱落，影响正常行车',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '立墙或立柱产生严重倾斜，或出现严重开裂、脱落，导致桥面出现严重塌陷或沉降，变形过大，不能正常行车',
        quantifier: '—',
      },
    ],
  },
  {
    id: '6',
    name: '拱上结构裂缝',
    sequence: 6,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '拱上立柱(立墙)上下端水平裂缝、盖梁和横系梁裂缝、腹拱拱顶、拱脚径向裂缝、梁板跨中竖向裂缝：少量裂缝，缝宽未超限',
        quantifier: '缝长≤截面尺寸的1/8（水平裂缝）或1/3（其他裂缝）',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '拱上立柱(立墙)上下端水平裂缝、盖梁和横系梁裂缝、腹拱拱顶、拱脚径向裂缝、梁板跨中竖向裂缝：较多裂缝，缝宽未超限',
        quantifier: '缝长>截面尺寸的1/8且≤1/2（水平裂缝）或>1/3且≤2/3（其他裂缝），间距≥20cm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '拱上立柱(立墙)上下端水平裂缝、盖梁和横系梁裂缝、腹拱拱顶、拱脚径向裂缝、梁板跨中竖向裂缝：有大量裂缝，部分缝宽超限',
        quantifier: '缝长>截面尺寸的1/2（水平裂缝）或>2/3（其他裂缝），间距<20cm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '6',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
  {
    id: '7',
    name: '拱上填料排水不畅',
    sequence: 7,
    catalogId: '6-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '排水不畅，导致侧墙出现渗水',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '排水不畅，填土聚积水分，导致侧墙出现轻微鼓肚',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '排水不畅，填土聚积大量水分，导致侧墙出现渗水甚至变形',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '7',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
];
