export const section_7_2 = [
  {
    id: '1',
    name: '错位、滑移',
    sequence: 1,
    catalogId: '7-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '无移动',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '-',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '个别索夹有错位、移动',
        quantifier: '滑移量≤10mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '较多索夹有明显错位、滑动现象;个别索夹位移超限',
        quantifier: '滑移量>10mm',
      },
    ],
  },
  {
    id: '2',
    name: '面漆起皮',
    sequence: 2,
    catalogId: '7-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '索夹面漆局部起皮',
        quantifier: '索夹起皮的数量≤总数量的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '索夹面漆局部起皮,并伴有锈蚀',
        quantifier: '索夹起皮的数量>总数量的5%且≤总数量的20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '索夹面漆起皮,锈蚀严重',
        quantifier: '索夹起皮、锈蚀的数量>总数量的20%',
      },
    ],
  },
  {
    id: '3',
    name: '索夹密封填料损坏',
    sequence: 3,
    catalogId: '7-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '索夹填料局部轻微老化,表面有脏污',
        quantifier: '数量≤总数量的3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '索夹填料老化、局部有开裂剥落,部分发生变形',
        quantifier: '数量>总数量的3%且≤总数量的10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '索夹填料老化、局部有开裂剥落',
        quantifier: '数量>总数量的10%',
      },
    ],
  },
  {
    id: '4',
    name: '裂纹和锈蚀',
    sequence: 4,
    catalogId: '7-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '索夹个别部位出现明显轻微裂纹,或表面有少量点蚀、锈斑',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '大量索夹外观有较多明显裂缝,或表面普遍有点蚀、锈斑或锈坑',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '大量夹壁开裂,索夹眼板开裂,索夹严重锈蚀',
        quantifier: '',
      },
    ],
  },
];
