export const section_8_2 = [
  {
    id: '1',
    name: '漆膜损坏',
    sequence: 1,
    catalogId: '8-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '各部分油漆均匀平光、完整,色泽鲜明',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '油漆变色、轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计失效面积≤构件面积的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '较大范围涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计失效面积>构件面积的10%且≤构件面积的20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '大范围涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计失效面积>构件面积的20%',
      },
    ],
  },
  {
    id: '2',
    name: '护套裂缝',
    sequence: 2,
    catalogId: '8-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: 'PE管或金属管轻微胀裂,未造成渗水等;或热挤PE护套轻微开裂,未造成其他影响,符合相关要求',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: 'PE管或金属管胀裂,出现较多纵向裂缝,造成渗水,钢丝有锈迹或护套内有氧化物,钢束截面削弱,但在规范范围内;或热挤PE护套产生环状开裂或PE层断开,造成渗水,导致钢丝锈蚀,但在规范范围内',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: 'PE管或金属管胀裂,出现很多纵向裂缝,渗水造成钢丝锈蚀和护套内有氧化物,钢束截面削弱超出规范范围;或热挤PE护套产生严重环状开裂或PE层断开,造成渗水,导致钢丝锈蚀超出规范范围',
        quantifier: '',
      },
    ],
  },
  {
    id: '3',
    name: '护套锈蚀',
    sequence: 3,
    catalogId: '8-2 -3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '参照表8.2.1-3标准评定',
        quantifier: '',
      },
    ],
  },
  {
    id: '4',
    name: '防护层破损',
    sequence: 4,
    catalogId: '8-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '个别防护层轻微老化或破损',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '个别防护层老化、破损、松动',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '部分防护层老化、破损、裂纹或积水,造成局部渗水或锈蚀;个别护筒甚至脱落',
        quantifier: '',
      },
    ],
  },
  {
    id: '5',
    name: '护套上端浆液离析',
    sequence: 5,
    catalogId: '8-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '局部离析',
        quantifier: '≤10%的浆液没有凝固',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '局部离析,浆液有流动性',
        quantifier: '>10%的浆液没有凝固',
      },
    ],
  },
  {
    id: '6',
    name: '渗水',
    sequence: 6,
    catalogId: '8-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '个别护套轻微渗水',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '个别护套明显渗水;个别渗水处伴有锈蚀',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '多处护套明显渗水,渗水处伴有锈蚀',
        quantifier: '',
      },
    ],
  },
];
