export const section_8_1 = [
  {
    id: '1',
    name: '拉索锈蚀、断丝',
    sequence: 1,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '钢丝有极少量锈蚀',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '钢丝少量锈蚀,钢丝无断裂',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '钢丝较多锈蚀或损坏,钢丝断裂,截面出现削弱',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '钢索裸露,钢丝大量严重锈蚀或损坏,钢丝断裂,主梁出现严重变形,造成安全隐患',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '滑移变位',
    sequence: 2,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '斜拉索出现异常位移变形,且无法复位',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '2',
        qualitative: '斜拉索异常位移变形过大,导致桥面线形、纵向位移伸缩量出现显著异常,结构振动或摇晃显著,影响结构安全',
        quantifier: '',
      },
    ],
  },
  {
    id: '3',
    name: '涂层损坏',
    sequence: 3,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '涂层有轻微损坏、裂纹、起皮或剥落',
        quantifier: '累计面积≤构件面积的10%,单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '较大范围涂层有损坏、裂纹、起皮、剥落',
        quantifier: '累计面积>构件面积的10%且≤构件面积的20%,单处面积≤1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '大范围涂层有损坏、裂纹、起皮或剥落',
        quantifier: '累计面积>构件面积的20%,单处面积>1.0m²',
      },
    ],
  },
  {
    id: '4',
    name: '护套内的材料老化变质',
    sequence: 4,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '护套内的材料轻微老化,表面有脏污',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '护套内的材料老化变形',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '护套内的材料老化变形,并有破裂现象,局部还造成渗水',
        quantifier: '',
      },
    ],
  },
  {
    id: '5',
    name: '锚固区损坏',
    sequence: 5,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '个别锚头或锚拉板出现轻微破损',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '个别锚头出现破损、松动或出现不密封现象,但未造成拉索锈蚀,个别锚拉板出现疲劳损伤状况',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '较多锚头或锚拉板出现破损、松动或裂缝,锚头锈蚀,锚固区有明显的受力裂缝',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '较多锚头或锚拉板出现严重破损、松动、裂缝,锚头积水锈蚀严重,锚固区有明显的受力裂缝,且缝宽>0.2mm',
        quantifier: '',
      },
    ],
  },
  {
    id: '6',
    name: '拉索线形异常',
    sequence: 6,
    catalogId: '8-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '拉索线形出现明显异常或有异常声音',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '6',
        qualitative: '拉索线形出现显著异常,桥面线形出现显著异常,结构振动摇明显,主梁出现严重变形',
        quantifier: '',
      },
    ],
  },
];
