export const section_7_1 = [
  {
    id: '1',
    name: '主缆防护损坏',
    sequence: 1,
    catalogId: '7-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '主缆防护表面有局部面漆变色起皮，个别位置出现破损、老化、漏水',
        quantifier: '面漆变色起皮面积≤3%，或防护破损面积≤1%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '主缆表面面漆有部分损坏、裂纹、变色起皮或剥落；局部位置出现破损、老化、漏水，或极少的部位缠丝外露，且没有生锈',
        quantifier: '防护破损面积>1%且≤10%，或缠丝外露数量≤3%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '主缆表面较大范围面漆有轻微损坏、裂纹、变色起皮或剥落；局部位置出现破损、老化、漏水，或局部缠丝外露并伴有生锈',
        quantifier: '缠丝外露数量>3%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '1',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
  {
    id: '2',
    name: '主缆线形',
    sequence: 2,
    catalogId: '7-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '主缆线形完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '主缆线形正常',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '主缆变形，但小于设计允许值',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '主缆变形较大，不可恢复的变化小于或等于设计允许值',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '2',
        qualitative: '主缆变形较为严重，不可恢复的变化大于设计允许值',
        quantifier: '—',
      },
    ],
  },
  {
    id: '3',
    name: '扶手绳及栏杆绳损坏',
    sequence: 3,
    catalogId: '7-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '检修道上扶手绳及栏杆绳有伤痕并有起丝现象',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '扶手绳、栏杆绳出现多处伤痕',
        quantifier: '截面损失>30%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '扶手绳或栏杆绳有断裂现象',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
  {
    id: '4',
    name: '主缆腐蚀或索股损坏',
    sequence: 4,
    catalogId: '7-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '主缆局部出现轻微脱皮、锈蚀、伤痕或有麻点，或镀锌钢丝出现少量锌腐蚀亮斑，失去光泽',
        quantifier: '—',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '主缆出现少量脱皮、伤痕或轻度至中度腐蚀，缠丝层有较多麻坑，或镀锌钢丝出现较多锌腐蚀，并有白色腐蚀产物，尚未见铁腐蚀',
        quantifier: '—',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '主缆出现较多脱皮、伤痕或密布的中等大小腐坑，缠丝层有大量的麻坑，或镀锌钢丝锌层减少，出现铁腐蚀斑点和腐坑',
        quantifier: '—',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '主缆缠丝防锈层已经严重腐蚀、断丝，或出现严重脱皮、伤痕、断丝，或镀锌钢丝严重腐蚀、断丝',
        quantifier: '—',
      },
    ],
  },
  {
    id: '5',
    name: '涂膜劣化',
    sequence: 5,
    catalogId: '7-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '构件表面出现轻微起泡、裂纹、脱落现象，或构件表面出现轻微粉化现象',
        quantifier: '起泡、裂纹、脱落、粉化累计面积≤构件面积的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '构件表面出现中等起泡、裂纹、脱落现象，或构件表面出现中等粉化或锈蚀现象',
        quantifier: '起泡、裂纹、脱落、粉化、锈蚀累计面积>构件面积的10%且≤构件面积的20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '构件表面出现较严重起泡、裂纹、脱落现象，或构件表面出现较严重粉化或锈蚀现象，轻轻擦抹涂层，粘有大量颜料粒子甚至出现漏底',
        quantifier: '起泡、裂纹、脱落粉化、锈蚀累计面积>构件面积的20%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '—',
        quantifier: '—',
      },
    ],
  },
];
