export const section_10_1_1 = [
  {
    id: '1',
    name: '变形',
    sequence: 1,
    catalogId: '10-1-1',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '局部出现波浪拥包 或 局部有高低不平的现象 或 局部出现车辙,深度较浅',
        quantifier: '波浪拥包面积≤10%，波峰波谷高差≤25mm 或 高低差≤25mm 或 铺装层出现车辙的面积＜10%，深度≤25mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '多处出现波浪拥包 或 多处有高低不平的现象',
        quantifier: '波浪拥包面积>10%且≤20%,波峰波谷高差≤25mm 或 高低差≤25mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '大面积出现波浪拥包 或 普遍有高低不平的现象 或 大面积出现车辙,深度较深',
        quantifier: '铺装层出现车辙的面积＞10%且≤20%，深度≤25mm 或 波浪拥包面积＞20%，波峰波谷高差＞25mm 或 铺装层出现车辙的面积＞20%，深度＞25mm',
      },
    ],
  },
  {
    id: '2',
    name: '泛油',
    sequence: 2,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '局部出现泛油',
        quantifier: '面积≤10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '多处出现泛油',
        quantifier: '面积>10%且≤20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '大面积出现泛油、磨光',
        quantifier: '面积>20%',
      },
    ],
  },
  {
    id: '3',
    name: '破损',
    sequence: 3,
    catalogId: '10-1-3',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '面层局部松散、露骨 或 局部浅坑槽',
        quantifier: '松散、露骨累计面积≤10% 或 坑槽深度≤25mm,累计面积≤3%,单处面积≤0.5m²',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '多处松散、露骨 或 多处出现坑槽',
        quantifier: '松散、露骨累计面积>10%且≤20% 或 坑槽深度≤25mm,累计面积>3%且≤10%,单处面积>0.5m²且≤1.0m²',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '大部分松散、露骨 或 大部分有坑槽',
        quantifier: '松散、露骨累计面积>20% 或 坑槽深度>25mm,累计面积>10%,单处面积>1.0m²',
      },
    ],
  },
  {
    id: '4',
    name: '裂缝（沥青混凝土）',
    sequence: 4,
    catalogId: '10-1-4',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '局部龟裂,裂缝区无变形、无散落 或 局部块裂,裂缝区无散落 或 有纵横裂缝,裂缝壁无散落,无支缝',
        quantifier: '龟裂缝宽≤2.0mm,部分裂缝块度≤5.0m 或 块裂缝宽≤3.0mm,大部分裂缝块度>1.0m 或 纵横裂缝缝长≤1.0m,缝宽≤3.0mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '局部龟裂,状态明显,裂缝区有轻度散落或变形 或 局部块裂,裂缝区有散落 或 有纵横裂缝,裂缝壁有散落,有支缝',
        quantifier: '龟裂缝宽>2.0mm且≤5.0mm,部分裂缝块度≤2.0m 或 块裂缝宽>3.0mm,大部分裂缝块度>0.5m且≤1.0m 或 纵横裂缝缝长>1.0m且≤2.0m,缝宽>3.0mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '多处龟裂,特征显著,裂缝区变形明显、散落严重 或 多处块裂,裂缝区散落严重 或 有纵横通缝,裂缝壁散落,支缝严重',
        quantifier: '龟裂缝宽>5.0mm,大部分裂缝块度≤2.0m 或 块裂缝宽>3.0mm,大部分裂缝块度≤0.5m 或 纵横裂缝长>2.0m,缝宽>3.0mm',
      },
    ],
  },
];

export const section_10_1_2 = [
  {
    id: '5',
    name: '错台',
    sequence: 5,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '局部接缝两侧出现高差现象',
        quantifier: '高差≤10mm',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '多处接缝两侧出现高差现象',
        quantifier: '高差>10mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '绝大多数接缝两侧出现高差现象',
        quantifier: '高差>10mm',
      },
    ],
  },
  {
    id: '6',
    name: '坑洞',
    sequence: 6,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '完好',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '局部出现坑洞',
        quantifier: '深度≤1cm,直径≤3cm,或累计面积≤3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '多处坑洞',
        quantifier: '深度>1cm,直径>3cm,或累计面积>3%且≤10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '大部分有坑洞',
        quantifier: '深度>1cm,直径>3cm,或累计面积>10%',
      },
    ],
  },
  {
    id: '7',
    name: '剥落',
    sequence: 7,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '局部接缝处出现浅层边角剥落,局部出现层状剥落',
        quantifier: '层状剥落累计面积≤10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '多处接缝处出现中、深层边角剥落,局部出现层状剥落',
        quantifier: '层状剥落累计面积>10%且≤20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '大部分接缝处出现深层边角剥落,局部出现层状剥落',
        quantifier: '层状剥落累计面积>20%',
      },
    ],
  },
  {
    id: '8',
    name: '拱起',
    sequence: 8,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '8',
        qualitative: '接缝两侧出现轻微抬高',
        quantifier: '接缝拱起条数≤总数的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '8',
        qualitative: '接缝两侧出现较大抬高',
        quantifier: '接缝拱起条数>总数的10%且≤总数的20%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '8',
        qualitative: '接缝两侧出现明显抬高',
        quantifier: '接缝拱起条数>总数的20%',
      },
    ],
  },
  {
    id: '9',
    name: '接缝料损坏',
    sequence: 9,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '9',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '9',
        qualitative: '接缝处填料老化、漏水,但尚未出现剥落、脱空,或被杂物填塞现象',
        quantifier: '填料老化、漏水≤整条缝的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '9',
        qualitative: '接缝处填料老化、漏水,部分填料脱空,或被杂物填塞',
        quantifier: '填料老化、漏水>整条缝的10%且≤整条缝的20%,或脱空、填塞长度≤接缝长的1/3',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '9',
        qualitative: '接缝处填料老化、漏水,多处填料脱空,或被杂物填塞',
        quantifier: '填料老化、漏水>整条缝20%,或脱空、填塞长度>接缝长的1/3',
      },
    ],
  },
  {
    id: '10',
    name: '裂缝（水泥混凝土）',
    sequence: 10,
    catalogId: '10-1-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '10',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '10',
        qualitative: '局部存在横向裂缝、纵向裂缝或斜裂缝,但未贯通 或 板角处裂缝与纵横接缝相交 或 局部出现破碎板,但未发生松动、沉陷等病害',
        quantifier: '裂缝缝宽<3mm 或 交点距角≤1/2板边长,裂缝缝宽<3mm 或 每块板被分成2~3块',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '10',
        qualitative: '多数存在横向裂缝、纵向裂缝或斜裂缝,边缘有碎裂 或 板角处裂缝与纵横向接缝相交,边缘存在碎裂 或 出现较多破碎板,板块伴有松动、沉陷、唧泥等现象',
        quantifier: '裂缝缝宽≥3mm且≤10mm 或 交点距角≤1/2板块边长,裂缝缝宽≥3mm且≤10mm 或 每块板被分成3~4块',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '10',
        qualitative: '大部分存在横向裂缝、纵向裂缝或斜裂缝,边缘有碎裂,并伴有错台出现 或 板角处裂缝与纵横向接缝相交,断角有松动 或 出现大量破碎板,板块伴有松动、沉陷、唧泥等现象',
        quantifier: '裂缝缝宽>10mm 或 交点距角≤1/2板块边长,缝宽>10mm 或 每块板被分成4块以上',
      },
    ],
  },
];

export const section_10_1 = [
  ...section_10_1_1,
  ...section_10_1_2,
];
