export const section_7_6 = [
  {
    id: '1',
    name: '上座板与下座板的相对位移',
    sequence: 1,
    catalogId: '7-6',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '上座板与下座板有相对位移',
        quantifier: '',
      },
    ],
  },
  {
    id: '2',
    name: '鞍座螺杆、锚栓状况',
    sequence: 2,
    catalogId: '7-6',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '个别螺杆、锚栓连接出现松动',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '少部分螺杆、锚栓连接出现松动',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '较多数量的螺杆、锚栓连接松动,个别螺杆、锚栓连接脱落',
        quantifier: '',
      },
    ],
  },
  {
    id: '3',
    name: '锈蚀',
    sequence: 3,
    catalogId: '7-6',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '构件表面有轻微锈蚀,但无可见油脂和污垢,且没有附着不牢的氧化皮、铁锈和油漆层',
        quantifier: '锈蚀面积≤构件面积的3%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '构件表面锈蚀,且部分氧化皮或油漆层剥落',
        quantifier: '锈蚀面积>构件面积的3%且≤构件面积的5%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '构件表面有大量点蚀现象,氧化皮或油漆层因锈蚀而部分剥落或者可以刮除',
        quantifier: '锈蚀面积>构件面积的5%',
      },
    ],
  },
];
