export const section_5_2 = [
  {
    id: '1',
    name: '涂层劣化',
    sequence: 1,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '1',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '1',
        qualitative: '涂层个别位置出现流痕、气泡、白化、漆膜发黏、针孔、起皱或皱纹、表面粉化、变色起皮、脱落等缺陷',
        quantifier: '累计面积≤构件面积的10%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '1',
        qualitative: '涂层出现较严重流痕、气泡、白化、漆膜发黏、针孔、起皱或皱纹、表面粉化、变色起皮、脱落等缺陷',
        quantifier: '累计面积>构件面积的10%且≤构件面积的50%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '1',
        qualitative: '涂层出现严重流痕、气泡、白化、漆膜发黏、针孔、起皱或皱纹、表面粉化、变色起皮、脱落等缺陷',
        quantifier: '累计面积>构件面积的50%',
      },
    ],
  },
  {
    id: '2',
    name: '锈蚀',
    sequence: 2,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '2',
        qualitative: '完好',
        quantifier: '—',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '2',
        qualitative: '构件表面发生轻微锈蚀，部分氧化皮或油漆层出现剥落',
        quantifier: '锈蚀累计面积 ≤ 构件面积的5%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '2',
        qualitative: '构件表面有较多点蚀现象，氧化皮、油漆层因锈蚀而部分剥落或可以刮除，重要部位有锈蚀成洞现象',
        quantifier: '锈蚀累计面积 > 构件面积的5%且 ≤ 构件面积的15%，或锈蚀孔洞 ≤ 3个；工字梁孔洞直径 ≤ 30mm，板梁 ≤ 50mm，且边缘完好；桁梁孔洞直径 ≤ 30mm，且 ≤ 杆件宽度的15%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '2',
        qualitative: '构件表面有大量点蚀现象，氧化皮、油漆层因锈蚀而全面剥离，重要部位被锈蚀成洞',
        quantifier: '锈蚀累计面积 > 构件面积的15%，或锈蚀孔洞 > 3个；工字梁孔洞直径 > 30mm，板梁 > 50mm，且边缘完好；桁梁孔洞直径 > 30mm，或 > 杆件宽度的15%',
      },
    ],
  },
  {
    id: '3',
    name: '焊缝开裂',
    sequence: 3,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '3',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '3',
        qualitative: '焊缝部位涂层有少量裂纹',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '3',
        qualitative: '焊缝部位涂层有大量裂纹,受拉翼缘边焊缝存在裂缝,其他部位焊缝无裂缝',
        quantifier: '主梁、纵横梁受拉翼缘边焊缝开裂长度≤5mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '3',
        qualitative: '主要构件焊缝出现较多裂缝,构件出现变形',
        quantifier: '主梁、纵横梁受拉翼缘边焊缝开裂长度>5mm且≤10mm,其他位置焊缝开裂长度≤5mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '3',
        qualitative: '主要构件焊缝存在大量裂缝甚至完全开裂,主要构件存在明显的变形,变形大于规范值',
        quantifier: '主梁、纵横梁受拉翼缘边焊缝开裂长度>10mm,其他位置焊缝开裂长度>5mm',
      },
    ],
  },
  {
    id: '4',
    name: '铆钉（螺栓）损失',
    sequence: 4,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '4',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '4',
        qualitative: '铆钉(螺栓)少量损坏、松动或丢失,造成联结部位铆钉(螺栓)失效',
        quantifier: '损坏、失效数量≤总量的1%',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '4',
        qualitative: '铆钉(螺栓)有较多损坏、松动或丢失,造成联结部位铆钉(螺栓)失效',
        quantifier: '损坏、失效数量>总量的1%且≤总量的10%',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '4',
        qualitative: '主要构件铆钉(螺栓)有较多损坏、松动或丢失,造成联结部位铆钉(螺栓)失效,构件出现明显变形',
        quantifier: '损坏、失效数量>总量的10%且≤总量的30%',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '4',
        qualitative: '主要构件铆钉(螺栓)有大量损坏、松动或丢失,造成联结部位铆钉(螺栓)失效,主要构件存在明显的永久变形,变形大于规范值',
        quantifier: '损坏、失效数量>总量的30%',
      },
    ],
  },
  {
    id: '5',
    name: '构件裂缝',
    sequence: 5,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '5',
        qualitative: '完好',
        quantifier: '-',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '5',
        qualitative: '钢构件出现极少量细小裂纹',
        quantifier: '-',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '5',
        qualitative: '钢构件出现较多细小裂缝,截面削弱,但不影响正常使用',
        quantifier: '主梁、纵横梁受拉翼缘边裂缝长度≤3mm,或受拉翼缘焊接盖板端部裂缝长度≤10mm,或桁梁端横梁与纵梁连接处下端以及腹杆接头处裂缝长度≤20mm',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '5',
        qualitative: '主要构件出现较多裂缝,截面削弱',
        quantifier: '主梁、纵横梁受拉翼缘边裂缝长度>3mm且≤5mm,或受拉翼缘焊接盖板端部裂缝长度>10mm且≤20mm,或桁梁端横梁与纵梁连接处下端以及腹杆接头处裂缝长度>20mm且≤50mm',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '5',
        qualitative: '主要构件出现较多严重裂缝,截面削弱,主要构件存在明显的永久变形,变形大于限值',
        quantifier: '主梁、纵横梁受拉翼缘边裂缝长度>5mm,或受拉翼缘焊接盖板端部裂缝长度>20mm,或桁梁端横梁与纵梁连接处下端以及腹杆接头处裂缝长度≤50mm',
      },
    ],
  },
  {
    id: '6',
    name: '跨中挠度',
    sequence: 6,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '6',
        qualitative: '完好',
        quantifier: '一',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '6',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '6',
        qualitative: '挠度小于限值',
        quantifier: '简支或连续板梁跨中最大挠度≤计算跨径的1/800;或简支或连续桁架跨中最大挠度≤计算跨径的1/1000',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '6',
        qualitative: '主要构件挠度接近限值,裂缝状况较严重',
        quantifier: '简支或连续板梁跨中最大挠度>计算跨径的1/800且≤计算跨径的1/600;或简支或连续桁架跨中最大挠度>计算跨径的1/1000且≤计算跨径的1/800',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '6',
        qualitative: '主要构件挠度大于限值,存在明显的永久变形,裂缝状况严重,严重影响承载力,有不正常移动并影响结构安全',
        quantifier: '简支或连续板梁跨中最大挠度>计算跨径的1/600;或简支或连续桁架跨中最大挠度>计算跨径的1/800',
      },
    ],
  },
  {
    id: '7',
    name: '构件变形',
    sequence: 7,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '7',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '7',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '7',
        qualitative: '个别次要构件出现异常变形,行车稍感振动或摇晃',
        quantifier: '构件竖向弯曲矢度≤跨度的1/1500;或板梁、纵梁、横梁及工字梁横向弯曲矢度≤自由长度1/8000且<15mm;或桁梁的压力杆件弯曲矢度≤杆件自由长度的1/1500;或拉力杆件弯曲矢度≤杆件自由长度的1/800,腹杆、连接杆件弯曲矢度≤杆件自由长度的1/500',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '7',
        qualitative: '个别主要承重构件出现异常变形,行车有明显振动或摇晃并伴有异常声音',
        quantifier: '构件竖向弯曲矢度>跨度的1/1500且≤跨度的1/1000;或板梁、纵梁、横梁及工字梁横向弯曲矢度>自由长度的1/8000且≤自由长度的1/5000,且<20mm;或桁梁的压力杆件弯曲矢度杆件>自由长度的1/1500且≤自由长度的1/1000;或拉力杆件弯曲矢度>杆件自由长度的1/800且≤杆件自由长度的1/500,腹杆、连接杆件弯曲矢度>杆件自由长度的1/500且≤杆件自由长度的1/300',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '7',
        qualitative: '较多主要承重构件有异常变形,变形大于规范值,影响桥梁结构安全',
        quantifier: '构件竖向弯曲矢度>跨度的1/1000;或板梁、纵梁、横梁及工字梁横向弯曲矢度>自由长度1/5000且>20mm;或桁梁的压力杆件弯曲矢度>杆件自由长度的1/1000;或拉力杆件弯曲矢度>杆件自由长度的1/500,腹杆、连接杆件弯曲矢度>杆件自由长度的1/300',
      },
    ],
  },
  {
    id: '8',
    name: '结构变位',
    sequence: 8,
    catalogId: '5-2',
    standards: [
      {
        id: '1',
        scale: 1,
        indicatorId: '8',
        qualitative: '完好',
        quantifier: '',
      },
      {
        id: '2',
        scale: 2,
        indicatorId: '8',
        qualitative: '',
        quantifier: '',
      },
      {
        id: '3',
        scale: 3,
        indicatorId: '8',
        qualitative: '横向联结件出现松动,纵向接缝开裂较大',
        quantifier: '',
      },
      {
        id: '4',
        scale: 4,
        indicatorId: '8',
        qualitative: '主要构件存在明显的永久变形,变形小于或等于规范值,或桥面竖向呈波形',
        quantifier: '',
      },
      {
        id: '5',
        scale: 5,
        indicatorId: '8',
        qualitative: '主要构件存在明显的永久变形,变形大于规范值,结构振动或摇晃显著、有不正常移动',
        quantifier: '',
      },
    ],
  },
];
